# Generated by Django 6.0.2 on 2026-02-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=255)),
                ('ingredients', models.TextField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('stock', models.PositiveSmallIntegerField()),
                ('discount', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
